---
- shell: setup-xorg-base

- apk:
    name: "{{ item }}"
  with_items:
    - alpine-desktop
    - setxkbmap
    - faenza-icon-theme

- service: 
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dbus
    - lxdm

- file: path=/etc/X11/xinit/xinitrc.d/99-xkbmap state=touch owner=root group=root mode=0755
- lineinfile: dest=/etc/X11/xinit/xinitrc.d/99-xkbmap line='setxkbmap jp'

